# This is a basic workflow that is manually triggered

name: nighlty_codecov

# Controls when the action will run. CRON schedule runs at mm hh dd mm yy UTC TIME
on:
  schedule:
    - cron: "57 10 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Make the default shell a login shell, so that conda is initialised properly
    defaults:
      run:
        shell: bash -el {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        python-version: "3.10"
    - name: pip install
      run:  |
        pip install wakis['notebook']
        pip install pytest pytest-cov
    - name: Print versions
      run: conda list
    - name: Checkout wakis
      uses: actions/checkout@v4
      with:
        path: wakis
    - name: Run pytest
      run:  |
        cd wakis
        pytest --cov --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV }}
        slug: ImpedanCEI/wakis